/**
 * A default ModelVector catalog of current models with REAL, sourced capability
 * scores.
 *
 * HONESTY: routing targets are the current model ids, but published benchmarks do
 * not yet exist for every current version. Where they do not, a model's scores are
 * carried forward from its family's latest MEASURED version (capability persists
 * across versions), and `profileFrom` names that source so the numbers are never
 * mistaken for the current model's own. Absent scores are left out (never guessed);
 * the router degrades gracefully over the gaps. These are refreshed as new
 * benchmarks land. Sources per axis: SWE-bench Verified (code_agentic),
 * LiveCodeBench (code_snippet), GPQA Diamond + AIME 2025 (math_reasoning), MMLU-Pro
 * (general_knowledge), IFEval (instruction_following), BFCL (tool_use), MMMLU/MGSM
 * (multilingual), EQ-Bench (creative_writing), MMMU (vision_score), LMArena Elo
 * (human_preference_elo, min-max normalised), Artificial Analysis (latency).
 */

import type { ModelVector } from "./modelVector";

function model(
  over: Partial<ModelVector> &
    Pick<
      ModelVector,
      "id" | "family" | "priceTier" | "pricePerMTokens" | "context"
    >,
): ModelVector {
  return {
    modelClass: "chat",
    imageIn: false,
    audioIn: false,
    videoIn: false,
    toolsSupported: true,
    hasWebSearch: false,
    scores: {},
    ...over,
  };
}

/** Current models, scored from their family's latest measured version (see profileFrom). */
export const defaultVectorCatalog: ModelVector[] = [
  model({
    id: "anthropic/claude-opus-5",
    family: "Claude",
    priceTier: "premium",
    pricePerMTokens: 25,
    context: 1000000,
    imageIn: true,
    profileFrom: "claude-3.5-sonnet",
    scores: {
      code_agentic: 0.49,
      code_snippet: 0.389,
      math_reasoning: 0.65,
      general_knowledge: 0.78,
      instruction_following: 0.865,
      tool_use: 0.5646,
      multilingual: 0.916,
      creative_writing: 0.83,
      vision_score: 0.704,
      human_preference_elo: 0.5922,
    },
  }),
  model({
    id: "anthropic/claude-haiku-4.5",
    family: "Claude",
    priceTier: "mid",
    pricePerMTokens: 5,
    context: 200000,
    imageIn: true,
    profileFrom: "claude-3.5-haiku",
    scores: {
      code_agentic: 0.406,
      math_reasoning: 0.416,
      general_knowledge: 0.65,
      tool_use: 0.5327,
      human_preference_elo: 0.3464,
    },
  }),
  model({
    id: "openai/gpt-5.6-sol",
    family: "GPT",
    priceTier: "premium",
    pricePerMTokens: 30,
    context: 1050000,
    imageIn: true,
    profileFrom: "gpt-4o",
    scores: {
      code_agentic: 0.332,
      code_snippet: 0.329,
      math_reasoning: 0.499,
      general_knowledge: 0.726,
      instruction_following: 0.843,
      tool_use: 0.6958,
      multilingual: 0.814,
      creative_writing: 0.7561,
      vision_score: 0.691,
      human_preference_elo: 0.514,
      latency: 0.4871,
    },
  }),
  model({
    id: "openai/gpt-5.3-codex",
    family: "GPT",
    priceTier: "premium",
    pricePerMTokens: 14,
    context: 400000,
    imageIn: true,
    profileFrom: "o1",
    scores: {
      code_agentic: 0.489,
      code_snippet: 0.634,
      math_reasoning: 0.757,
      tool_use: 0.5449,
      multilingual: 0.877,
      vision_score: 0.782,
      human_preference_elo: 0.9609,
    },
  }),
  model({
    id: "openai/gpt-5-nano",
    family: "GPT",
    priceTier: "cheap",
    pricePerMTokens: 0.4,
    context: 400000,
    imageIn: true,
    profileFrom: "gpt-4o-mini",
    scores: {
      math_reasoning: 0.402,
      instruction_following: 0.804,
      tool_use: 0.641,
      multilingual: 0.705,
      creative_writing: 0.7841,
      vision_score: 0.594,
      human_preference_elo: 0.5307,
      latency: 0.333,
    },
  }),
  model({
    id: "google/gemini-3.1-pro-preview",
    family: "Gemini",
    priceTier: "premium",
    pricePerMTokens: 12,
    context: 1048576,
    imageIn: true,
    audioIn: true,
    videoIn: true,
    profileFrom: "gemini-1.5-pro",
    scores: {
      math_reasoning: 0.5833,
      general_knowledge: 0.758,
      tool_use: 0.6097,
      multilingual: 0.875,
      creative_writing: 0.8144,
      vision_score: 0.622,
      human_preference_elo: 0.7095,
    },
  }),
  model({
    id: "google/gemini-3.7-flash",
    family: "Gemini",
    priceTier: "mid",
    pricePerMTokens: 1.88,
    context: 1048576,
    imageIn: true,
    audioIn: true,
    videoIn: true,
    profileFrom: "gemini-2.0-flash",
    scores: {
      math_reasoning: 0.6515,
      tool_use: 0.6059,
      creative_writing: 0.8141,
      vision_score: 0.717,
      human_preference_elo: 0.9162,
    },
  }),
  model({
    id: "google/gemini-2.5-flash-lite",
    family: "Gemini",
    priceTier: "cheap",
    pricePerMTokens: 0.4,
    context: 1048576,
    imageIn: true,
    audioIn: true,
    videoIn: true,
    profileFrom: "gemini-1.5-flash",
    scores: {
      math_reasoning: 0.4596,
      general_knowledge: 0.673,
      tool_use: 0.5628,
      multilingual: 0.826,
      creative_writing: 0.7196,
      vision_score: 0.561,
      human_preference_elo: 0.5363,
    },
  }),
  model({
    id: "deepseek/deepseek-v4-pro",
    family: "DeepSeek",
    priceTier: "mid",
    pricePerMTokens: 1.98,
    context: 1048576,
    profileFrom: "deepseek-r1",
    scores: {
      code_agentic: 0.492,
      code_snippet: 0.659,
      math_reasoning: 0.715,
      general_knowledge: 0.84,
      instruction_following: 0.833,
      tool_use: 0.5689,
      creative_writing: 0.8711,
      human_preference_elo: 1.0,
    },
  }),
  model({
    id: "deepseek/deepseek-v4-flash",
    family: "DeepSeek",
    priceTier: "cheap",
    pricePerMTokens: 0.17,
    context: 1048576,
    profileFrom: "deepseek-v3",
    scores: {
      code_agentic: 0.42,
      code_snippet: 0.405,
      math_reasoning: 0.591,
      general_knowledge: 0.759,
      instruction_following: 0.861,
      tool_use: 0.5723,
      multilingual: 0.798,
      creative_writing: 0.8119,
      human_preference_elo: 0.7821,
    },
  }),
  model({
    id: "qwen/qwen3-coder-flash",
    family: "Qwen",
    priceTier: "cheap",
    pricePerMTokens: 0.98,
    context: 1000000,
    profileFrom: "qwen-2.5-coder-32b",
    scores: {
      code_snippet: 0.314,
      instruction_following: 0.799,
      human_preference_elo: 0.2291,
    },
  }),
  model({
    id: "meta-llama/llama-4-scout",
    family: "Llama",
    priceTier: "cheap",
    pricePerMTokens: 0.3,
    context: 1310720,
    imageIn: true,
    profileFrom: "llama-3.3-70b-instruct",
    scores: {
      math_reasoning: 0.505,
      general_knowledge: 0.689,
      tool_use: 0.5143,
      multilingual: 0.911,
      human_preference_elo: 0.4749,
      latency: 0.266,
    },
  }),
  model({
    id: "mistralai/mistral-large",
    family: "Mistral",
    priceTier: "mid",
    pricePerMTokens: 6,
    context: 128000,
    profileFrom: "mistral-large (measured)",
    scores: {
      math_reasoning: 0.4773,
      tool_use: 0.5845,
      multilingual: 0.8901,
      creative_writing: 0.7717,
      human_preference_elo: 0.419,
    },
  }),
  model({
    id: "perplexity/sonar-pro",
    family: "Perplexity",
    priceTier: "premium",
    pricePerMTokens: 15,
    context: 200000,
    imageIn: true,
    toolsSupported: false,
    hasWebSearch: true,
    profileFrom: "n/a (live web-search specialist; no chat benchmark)",
  }),
  model({
    id: "perplexity/sonar",
    family: "Perplexity",
    priceTier: "cheap",
    pricePerMTokens: 1,
    context: 127072,
    imageIn: true,
    toolsSupported: false,
    hasWebSearch: true,
    profileFrom: "n/a (live web-search specialist; no chat benchmark)",
  }),
];
